- name: Deploy nginx
  hosts: all
  become: true
  tasks:
    - name: "Install Nginx"
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: "Remove nginx default config"
      ansible.builtin.file:
        path: /etc/nginx/nginx.conf
        state: absent
    
    - name: "Template admin migration"
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: "Give user www-data access to user ubuntu's home directory"
      command: setfacl -R -m u:www-data:rwx ~ubuntu

    - name: "Restart Nginx"
      service:
        name: nginx
        state: restarted
